### ISSUE TITLE
agent load/premain call failed during start

### ISSUE THREAD

**Issue by lunmag** [elbosso/swinginspector#7]
Hi!
Taking a wild shot to see if You have any idea regarding an error.
I'm desperately trying to do some automation and it's pretty hard to find Swing stuff...
I've tested with two JARs with same outcome
Thanks,
Magnus

```
C:\tests\Retail\swinginspector>java -javaagent:swinginspector-1.3.0-SNAPSHOT-jar-with-dependencies.jar -jar atg-terminalen-2.16270_master_698.jar
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:517)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:527)
Caused by: java.lang.NoClassDefFoundError: ch/qos/logback/classic/Level
        at de.elbosso.ui.debug.inspector.Manager.premain(Manager.java:128)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.Level
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        ... 7 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at t:\workspace\open\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
```

**Comment by elbosso** [comment]
Oh - i made a mistake here. going to clean up this mess. Locally it already is fixed, currently preparing the new release...
